dist: trusty
sudo: required
services:
  - redis-server
  
language: php

php:
  - 7.0

before_install:
  - chmod +x ./scripts/*
  - ./scripts/travis_mysql_5.7.sh
  - ./scripts/mysql-reset-root-password.sh

before_script:
  - cp ./scripts/.env.travis ./.env
  - mysql -u root -e 'create database forge;'
  - composer self-update
  - composer install --no-interaction
  - php artisan setup:initialize admin@iserveu.ca abcd1234 yes

script:
  - vendor/bin/phpunit