dist: trusty
sudo: required
services:
- redis-server
language: php
php:
 - 7.0
notifications:
  email: false
before_install:
- chmod +x ./tests/scripts/*
- ./tests/scripts/install-node.sh
- ./tests/scripts/install-mysql.sh
- ./tests/scripts/install-protractor.sh
- sudo npm install -g bower
- sudo npm install -g gulp
before_script:
- cp ./tests/scripts/.env.travis ./.env
- cp ./tests/scripts/protractor.conf.js.travis ./protractor.conf.js
- mysql -u root -e 'create database forge;'
- composer install --no-interaction
- yarn
- bower update
- npm rebuild node-sass
- gulp
- php artisan route:cache
- php artisan config:cache
- php artisan optimize --force
- php artisan setup:initialize admin@iserveu.ca abcd1234 yes yes
- php artisan serve &
script:
- vendor/bin/phpunit
- protractor protractor.conf.js
- php artisan setup:initialize admin@iserveu.ca abcd1234 yes yes
after_script:
- ./tests/scripts/codeclimate.sh
cache:
  yarn: true
  directories:
  - node_modules
  - vendor
  - bower
  - $HOME/.composer/cache
env:
  global:
  - SELENIUM_HOST=hub-cloud.browserstack.com
  - SELENIUM_PORT=8000
  - BROWSERSTACK_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BROWSERSTACK_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - BROWSERSTACK_DEBUG=true
  - BROWSERSTACK_LOCAL=true
  - BASE_URL=http://localhost:8000/
