dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database forge;'
  - composer self-update
  - composer install --no-interaction
  - php artisan setup:initialize -qn

script:
  - vendor/bin/phpunit