dist: trusty
sudo: required
services:
  - redis-server
  
language: php

php:
  - 7.0

before_install:
  - chmod +x ./scripts/*
  - ./scripts/travis_mysql_5.7.sh
  - ./scripts/mysql-reset-root-password.sh

before_script:
  - cp ./scripts/.env.travis ./.env
  - mysql -u root -e 'create database forge;'
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm install -g bower
  - bower install
  - gulp
  - php artisan route:cache
  - php artisan config:cache
  - php artisan optimize --force
  - php artisan setup:initialize admin@iserveu.ca abcd1234 yes yes

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 29f76f2c6bad2f7df69753e00afbaf3122bda681
