dist: trusty
sudo: required
services:
  - redis-server

language: php

php:
  - 7.0

before_install:
  - chmod +x ./tests/scripts/*
  - ./tests/scripts/travis_mysql_5.7.sh
  - ./tests/scripts/mysql-reset-root-password.sh

before_script:
  - cp ./tests/scripts/.env.travis ./.env
  - cp ./tests/scripts/protractor.conf.js.travis ./protractor.conf.js
  - mysql -u root -e 'create database forge;'
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm install -g bower
  - bower install
  - gulp
  - php artisan route:cache
  - php artisan config:cache
  - php artisan optimize --force
  - php artisan setup:initialize admin@iserveu.ca abcd1234 yes yes
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g protractor
  - webdriver-manager update
  - sleep 5
  - php artisan serve &

script:
  - protractor protractor.conf.js
  - vendor/bin/phpunit

after_script:
  - ./tests/scripts/codeclimate.sh
